{% set version = "1.7" %}

package:
  name: jq
  version: {{ version }}

source:
  fn: jq-{{ version }}.tar.gz
  url: https://github.com/stedolan/jq/releases/download/jq-{{ version }}/jq-{{ version }}.tar.gz
  sha256: 402a0d6975d946e6f4e484d1a84320414a0ff8eb6cf49d2c11d144d4d344db62

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - make
  host:
    - oniguruma 6.9.*
  run:
    - oniguruma 6.9.*

test:
  commands:
    - jq --help  # [not win]

about:
  home: http://stedolan.github.io/jq/
  license: MIT
  license_file: COPYING
  summary: A command-line JSON processor.

extra:
  recipe-maintainers:
    - jakirkham
