{% set version = "1.6" %}

package:
  name: jq
  version: {{ version }}

source:
  fn: jq-{{ version }}.tar.gz
  url: https://github.com/stedolan/jq/releases/download/jq-{{ version }}/jq-{{ version }}.tar.gz
  sha256: 5de8c8e29aaa3fb9cc6b47bb27299f271354ebb72514e3accadc7d38b5bbaa72

build:
  number: 1001
  skip: True  # [win and vc<14]

requirements:
  build:
    - autotools_clang_conda  # [win]
    - {{ compiler('c') }}
    - make  # [unix]
  host:
    - oniguruma 6.9.*
  run:
    - oniguruma 6.9.*

test:
  commands:
    - jq --help  # [not win]

about:
  home: http://stedolan.github.io/jq/
  license: MIT
  license_file: COPYING
  summary: A command-line JSON processor.

extra:
  recipe-maintainers:
    - jakirkham
