{% set name = "jq" %}
{% set version = "jq-1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("jq-", "") }}

source:
  url: https://github.com/jqlang/{{ name }}/releases/download/{{ version }}/{{ version }}.tar.gz
  sha256: 402a0d6975d946e6f4e484d1a84320414a0ff8eb6cf49d2c11d144d4d344db62

build:
  number: 0
  script: bash {{ RECIPE_DIR }}/install.sh

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - m2-base  # [win]
    - m2-make  # [win]
    - m2w64-toolchain  # [win]
    - make  # [not win]
  host:
    - oniguruma 6.9.*
  run:
    - oniguruma 6.9.*

test:
  commands:
    - jq --help

about:
  home: https://github.com/jqlang/jq
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A command-line JSON processor.

extra:
  recipe-maintainers:
    - jakirkham
    - kenodegard
