{% set name = "jq" %}
{% set version = "jq-1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("jq-", "") }}

source:
  url: https://github.com/jqlang/{{ name }}/archive/{{ version }}.tar.gz
  sha256: f755e813b88b494a5087502812cb35bc32e1544102345900707e8d71124caffc

build:
  number: 0
  script: bash {{ RECIPE_DIR }}/install.sh

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf  # [not win]
    - automake  # [not win]
    - libtool  # [not win]
    - m2-autoconf  # [win]
    - m2-automake-wrapper  # [win]
    - m2-libtool  # [win]
    - m2-make  # [win]
    - make  # [not win]
    - posix  # [win]
    - m2w64-toolchain  # [win]
  host:
    - oniguruma 6.9.*
  run:
    - oniguruma 6.9.*

test:
  commands:
    - jq --help

about:
  home: https://github.com/jqlang/jq
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A command-line JSON processor.

extra:
  recipe-maintainers:
    - jakirkham
    - kenodegard
