context:
  name: jq
  version: "1.8.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/jqlang/jq/releases/download/jq-${{ version }}/jq-${{ version }}.tar.gz
  sha256: 2be64e7129cecb11d5906290eba10af694fb9e3e7f9fc208a311dc33ca837eb0

build:
  script:
    # New recipe uses `build.bat` by default on Windows, but `.gitattributes` still uses `bld.bat`
    - if: win
      then: bld.bat
  number: 1

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - if: win
      then: autotools_clang_conda
      else: make
  host:
    - oniguruma >=6.9
  run:
    - oniguruma >=6.9

tests:
  - script:
      - jq --help

about:
  homepage: https://jqlang.org/
  summary: 'A command-line JSON processor'
  description: |
    jq is a lightweight and flexible command-line JSON processor akin to
    sed,awk,grep, and friends for JSON data. It's written in portable C and has
    zero runtime dependencies, allowing you to easily slice, filter, map, and
    transform structured data.
  license: MIT
  license_file: COPYING
  documentation: https://jqlang.org/
  repository: https://github.com/jqlang/jq

extra:
  recipe-maintainers:
    - jakirkham
    - "0xbe7a"
    - aywi
